module_name: JSON Module
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - seo
  - rich snippets
  - google
description_short: The JSON module adds rich snippets to your website helping your site's seo.
description: description.md
images:
  - image-1.png
license: AFL